-- ProManLog : jeu de données de démonstration (SQLite)
-- À exécuter après 01_schema.sql, ou automatiquement par l'API si la base est vide.

-- Comptes administrateurs de test (mot de passe : admin123)
-- Hash = SHA-256 de "admin123"
INSERT INTO Utilisateur (NomUtilisateur, MotDePasseHash, NomComplet, Role) VALUES
('admin',  '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Administrateur Principal',  'Admin'),
('admin2', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'Administrateur Secondaire', 'Admin');

INSERT INTO Client (TypeClient, Nom, Contact, Email, Telephone, Adresse) VALUES
('Entreprise', 'Logistique Atlas SARL', 'Karim Bennani', 'contact@atlas-log.ma', '0522334455', '12 Bd Zerktouni, Casablanca, Maroc'),
('Entreprise', 'AgroFrais Distribution', 'Sofia El Amrani', 'achats@agrofrais.com', '0537221100', 'Zone Industrielle, Rabat, Maroc'),
('Entreprise', 'BTP Construct', 'Yassine Tazi', 'y.tazi@btpconstruct.fr', '0524889977', '45 Av Mohammed V, Marrakech, Maroc'),
('Particulier', 'Nadia Alaoui', '', 'nadia.alaoui@gmail.com', '0661234567', '8 Rue des Orangers, Fès, Maroc'),
('Particulier', 'Omar Berrada', '', 'omar.berrada@mail.com', '0678901234', '23 Av Hassan II, Tanger, Maroc'),
('Entreprise', 'Atlantique Export SARL', 'Hicham Raji', 'contact@atlantique-export.ma', '0528556677', 'Zone Portuaire, Agadir, Maroc'),
('Entreprise', 'Nord Cargo Services', 'Amine Fahsi', 'a.fahsi@nordcargo.ma', '0539112233', 'Port Tanger Med, Tanger, Maroc'),
('Entreprise', 'Fret Ibérique SL', 'Carlos Muñoz', 'c.munoz@fretiberico.es', '+34956778899', 'Polígono El Fresno, Algésiras, Espagne'),
('Entreprise', 'TransEurope Cargo', 'Julien Moreau', 'j.moreau@transeurope.fr', '+33491223344', 'Zone Portuaire, Marseille, France'),
('Particulier', 'Youssef Amrani', '', 'y.amrani@gmail.com', '0667788990', '14 Rue Ibn Sina, Meknès, Maroc'),
('Entreprise', 'Sahara Minerals SA', 'Abdellah Bouzid', 'contact@saharaminerals.ma', '0528991122', 'Zone Industrielle, Laâyoune, Maroc'),
('Entreprise', 'Oriental Trading Co.', 'Nabil Cherkaoui', 'n.cherkaoui@oriental-trading.ma', '0536445566', 'Av Mohammed VI, Oujda, Maroc'),
('Particulier', 'Imane Benjelloun', '', 'imane.benjelloun@outlook.com', '0645332211', '5 Rue Allal Ben Abdellah, Kénitra, Maroc'),
('Entreprise', 'Atlas Bâtiment', 'Rachid Sabir', 'r.sabir@atlas-batiment.ma', '0524667788', 'Zone Artisanale, Essaouira, Maroc'),
('Entreprise', 'Deutsche Fracht GmbH', 'Klaus Weber', 'k.weber@deutschefracht.de', '+494012345678', 'Speicherstadt, Hambourg, Allemagne');

INSERT INTO Vehicule (Immatriculation, TypeVehicule, CapaciteKg, Kilometrage, Statut,
                      DernierEntretien, ProchainEntretien, ProchainControleTechnique, FinAssurance) VALUES
('AB-123-CD', 'Camion 19T', 12000, 145200, 'Disponible',
    date('now', '-2 months'), date('now', '+4 months'),
    date('now', '+8 months'), date('now', '+5 months')),
('EF-456-GH', 'Fourgon', 1500, 89300, 'EnMission',
    date('now', '-1 months'), date('now', '+5 months'),
    date('now', '+20 days'), date('now', '+11 months')),
('IJ-789-KL', 'Semi-remorque', 25000, 232800, 'EnMaintenance',
    date('now', '-7 months'), date('now', '+10 days'),
    date('now', '+6 months'), date('now', '+15 days')),
('MN-012-OP', 'Camion frigorifique', 8000, 67100, 'Disponible',
    date('now', '-3 months'), date('now', '+3 months'),
    date('now', '+10 months'), date('now', '+9 months')),
('QR-345-ST', 'Fourgon', 1200, 154900, 'EnMission',
    date('now', '-5 months'), date('now', '+25 days'),
    date('now', '+4 months'), date('now', '+7 months')),
('ST-678-UV', 'Tracteur routier Volvo FH16', 40000, 198500, 'Disponible',
    date('now', '-4 months'), date('now', '+2 months'),
    date('now', '+9 months'), date('now', '+6 months')),
('WX-901-YZ', 'Camion benne Renault', 15000, 76200, 'EnMission',
    date('now', '-2 months'), date('now', '+4 months'),
    date('now', '+5 months'), date('now', '+10 months')),
('AB-234-EF', 'Fourgonnette Peugeot Boxer', 800, 34500, 'Disponible',
    date('now', '-1 months'), date('now', '+5 months'),
    date('now', '+7 months'), date('now', '+8 months')),
('GH-567-IJ', 'Porte-conteneurs Scania', 28000, 210300, 'EnMaintenance',
    date('now', '-6 months'), date('now', '+12 days'),
    date('now', '+3 months'), date('now', '+2 months')),
('KL-890-MN', 'Camion citerne Iveco', 20000, 143700, 'Disponible',
    date('now', '-3 months'), date('now', '+3 months'),
    date('now', '+11 months'), date('now', '+4 months')),
('OP-123-QR', 'Camion plateau MAN', 18000, 98600, 'EnMission',
    date('now', '-2 months'), date('now', '+30 days'),
    date('now', '+8 months'), date('now', '+9 months')),
('ST-456-UV', 'Mini-bus Mercedes Sprinter', 2500, 45200, 'Disponible',
    date('now', '-5 months'), date('now', '+1 months'),
    date('now', '+6 months'), date('now', '+7 months')),
('WX-789-YZ', 'Camion grue Volvo FMX', 22000, 167800, 'EnMaintenance',
    date('now', '-8 months'), date('now', '+18 days'),
    date('now', '+4 months'), date('now', '+3 months')),
('AB-012-EF', 'Semi-remorque frigorifique DAF', 24000, 121400, 'EnMission',
    date('now', '-3 months'), date('now', '+4 months'),
    date('now', '+10 months'), date('now', '+12 months')),
('GH-345-IJ', 'Camion 26T Renault', 26000, 189200, 'Disponible',
    date('now', '-1 months'), date('now', '+6 months'),
    date('now', '+5 months'), date('now', '+6 months'));

INSERT INTO Employe (Nom, Prenom, Poste, DateEmbauche, Email, Telephone, Statut, Disponibilite,
                     NumeroPermis, CategoriesPermis, ExpirationPermis) VALUES
('Mansouri', 'Hassan', 'Chauffeur', '2019-03-11', 'h.mansouri@promanlog.com', '0611111111', 'Actif', 'EnMission',
    'P-458712', 'B,C,CE', date('now', '+3 years')),
('Ouazzani', 'Rachid', 'Chauffeur', '2021-09-01', 'r.ouazzani@promanlog.com', '0622222222', 'Actif', 'Disponible',
    'P-129034', 'B,C', date('now', '+25 days')),
('Chraibi', 'Leila', 'Chauffeur', '2022-06-15', 'l.chraibi@promanlog.com', '0633333333', 'Actif', 'EnMission',
    'P-778215', 'B,C,CE,D', date('now', '+2 years')),
('Fassi', 'Mehdi', 'Mecanicien', '2020-01-20', 'm.fassi@promanlog.com', '0644444444', 'Actif', 'Disponible',
    '', '', NULL),
('Idrissi', 'Salma', 'Gestionnaire', '2018-11-05', 's.idrissi@promanlog.com', '0655555555', 'Actif', 'Disponible',
    '', '', NULL),
('Ziani', 'Karim', 'Chauffeur', '2017-04-02', 'k.ziani@promanlog.com', '0666666666', 'Inactif', 'EnConge',
    'P-334561', 'B,C', date('now', '+1 years')),
('Benali', 'Sara', 'Chauffeur', '2023-02-10', 's.benali@promanlog.com', '0677889900', 'Actif', 'Disponible',
    'P-556123', 'B,C,CE', date('now', '+2 years')),
('Kabbaj', 'Yassine', 'Chauffeur', '2023-07-18', 'y.kabbaj@promanlog.com', '0688990011', 'Actif', 'EnMission',
    'P-667234', 'B,C', date('now', '+3 years')),
('Sabiri', 'Omar', 'Mecanicien', '2021-05-04', 'o.sabiri@promanlog.com', '0699001122', 'Actif', 'Disponible',
    '', '', NULL);

INSERT INTO Prestation (IdClient, IdVehicule, IdEmploye, AdresseDepart, AdresseArrivee,
                        DateHeure, TypeService, Prix, Statut) VALUES
(1, 2, 1, 'Casablanca - Port', 'Rabat - Zone Industrielle', datetime('now', '+2 hours'), 'Marchandise générale', 4500.00, 'EnCours'),
(2, 5, 3, 'Rabat - Entrepôt AgroFrais', 'Tanger - Marché de gros', datetime('now', '-1 hours'), 'Produits frais', 6200.00, 'EnCours'),
(3, 1, 2, 'Marrakech - Dépôt BTP', 'Agadir - Chantier Sud', datetime('now', '+3 days'), 'Matériaux de construction', 8900.00, 'Planifiee'),
(4, NULL, NULL, 'Fès - Centre ville', 'Meknès - Quartier Nord', datetime('now', '+5 days'), 'Déménagement', 2300.00, 'Planifiee'),
(1, 4, 1, 'Casablanca - Aïn Sebaâ', 'El Jadida - Port', datetime('now', '-6 days'), 'Produits surgelés', 3800.00, 'Terminee'),
(2, 4, 3, 'Rabat - Entrepôt AgroFrais', 'Casablanca - Marché central', datetime('now', '-12 days'), 'Produits frais', 2900.00, 'Terminee'),
(5, NULL, NULL, 'Tanger - Ville', 'Tétouan - Centre', datetime('now', '-3 days'), 'Transport mobilier', 1500.00, 'Annulee'),
(3, 1, 2, 'Marrakech - Dépôt BTP', 'Ouarzazate - Chantier Est', datetime('now', '-20 days'), 'Matériaux de construction', 7400.00, 'Terminee'),
(7, 6, 8, 'Tanger Med - Terminal', 'Casablanca - Port', datetime('now', '+6 hours'), 'Conteneurs export', 12500.00, 'EnCours'),
(8, 14, 7, 'Algésiras, Espagne', 'Tanger - Port', datetime('now', '+2 days'), 'Fret international réfrigéré', 15800.00, 'Planifiee'),
(9, NULL, NULL, 'Marseille, France', 'Casablanca - Port', datetime('now', '+7 days'), 'Import matériel industriel', 21000.00, 'Planifiee'),
(15, 9, 3, 'Hambourg, Allemagne', 'Tanger Med - Terminal', datetime('now', '-2 days'), 'Fret conteneurisé', 26400.00, 'Terminee');

INSERT INTO Historique (DateAction, TypeAction, TypeEntite, IdEntite, Description) VALUES
(datetime('now', '-25 days'), 'Creation', 'Client', 8, 'Création du client Fret Ibérique SL (Algésiras, Espagne)'),
(datetime('now', '-22 days'), 'Creation', 'Vehicule', 9, 'Ajout du véhicule GH-567-IJ (Porte-conteneurs Scania)'),
(datetime('now', '-20 days'), 'Creation', 'Prestation', 8, 'Création de la prestation numéro 8 (BTP Construct)'),
(datetime('now', '-18 days'), 'Creation', 'Employe', 8, 'Ajout de l''employé Yassine Kabbaj (Chauffeur)'),
(datetime('now', '-12 days'), 'Creation', 'Prestation', 6, 'Création de la prestation numéro 6 (AgroFrais Distribution)'),
(datetime('now', '-11 days'), 'ChangementStatut', 'Prestation', 6, 'Prestation numéro 6 : Planifiee vers Terminee'),
(datetime('now', '-9 days'), 'Creation', 'Client', 9, 'Création du client TransEurope Cargo (Marseille, France)'),
(datetime('now', '-7 days'), 'Creation', 'Vehicule', 5, 'Ajout du véhicule QR-345-ST (Fourgon)'),
(datetime('now', '-6 days'), 'Creation', 'Prestation', 5, 'Création de la prestation numéro 5 (Logistique Atlas SARL)'),
(datetime('now', '-5 days'), 'ChangementStatut', 'Prestation', 5, 'Prestation numéro 5 : EnCours vers Terminee'),
(datetime('now', '-4 days'), 'Creation', 'Prestation', 12, 'Création de la prestation numéro 12 (Deutsche Fracht GmbH)'),
(datetime('now', '-3 days'), 'ChangementStatut', 'Prestation', 7, 'Prestation numéro 7 : Planifiee vers Annulee'),
(datetime('now', '-2 days'), 'Creation', 'Client', 15, 'Création du client Deutsche Fracht GmbH (Hambourg, Allemagne)'),
(datetime('now', '-1 days'), 'ChangementStatut', 'Vehicule', 3, 'Véhicule IJ-789-KL : Disponible vers EnMaintenance'),
(datetime('now'), 'ChangementStatut', 'Prestation', 1, 'Prestation numéro 1 : Planifiee vers EnCours');

-- Prestations terminées des mois précédents (historique du chiffre d'affaires)
INSERT INTO Prestation (IdClient, IdVehicule, IdEmploye, AdresseDepart, AdresseArrivee,
                        DateHeure, TypeService, Prix, Statut) VALUES
(1, 1, 1, 'Casablanca - Port', 'Rabat - Zone Industrielle', datetime('now', '-1 months'), 'Marchandise générale', 7900.00, 'Terminee'),
(2, 2, 3, 'Rabat - Entrepôt AgroFrais', 'Fès - Marché central', datetime('now', '-1 months'), 'Produits frais', 5700.00, 'Terminee'),
(3, 1, 2, 'Marrakech - Dépôt BTP', 'Agadir - Chantier Sud', datetime('now', '-1 months'), 'Matériaux de construction', 7850.00, 'Terminee'),
(1, 4, 1, 'Casablanca - Aïn Sebaâ', 'Tanger - Port', datetime('now', '-1 months'), 'Produits surgelés', 5850.00, 'Terminee'),
(2, 5, 3, 'Rabat - Zone Industrielle', 'Oujda - Entrepôt Est', datetime('now', '-1 months'), 'Marchandise générale', 7450.00, 'Terminee'),
(3, 2, 2, 'Marrakech - Dépôt BTP', 'Safi - Chantier Port', datetime('now', '-1 months'), 'Matériaux de construction', 7950.00, 'Terminee'),
(6, 7, 7, 'Agadir - Zone Portuaire', 'Casablanca - Port', datetime('now', '-1 months'), 'Export agrumes', 8650.00, 'Terminee'),
(8, 10, 8, 'Tanger - Port', 'Algésiras, Espagne', datetime('now', '-1 months'), 'Fret international', 14900.00, 'Terminee'),
(1, 1, 1, 'Casablanca - Port', 'Rabat - Zone Industrielle', datetime('now', '-2 months'), 'Marchandise générale', 6800.00, 'Terminee'),
(2, 2, 3, 'Rabat - Entrepôt AgroFrais', 'Fès - Marché central', datetime('now', '-2 months'), 'Produits frais', 6850.00, 'Terminee'),
(3, 1, 2, 'Marrakech - Dépôt BTP', 'Agadir - Chantier Sud', datetime('now', '-2 months'), 'Matériaux de construction', 8100.00, 'Terminee'),
(1, 4, 1, 'Casablanca - Aïn Sebaâ', 'Tanger - Port', datetime('now', '-2 months'), 'Produits surgelés', 6500.00, 'Terminee'),
(2, 5, 3, 'Rabat - Zone Industrielle', 'Oujda - Entrepôt Est', datetime('now', '-2 months'), 'Marchandise générale', 7800.00, 'Terminee'),
(3, 2, 2, 'Marrakech - Dépôt BTP', 'Safi - Chantier Port', datetime('now', '-2 months'), 'Matériaux de construction', 7550.00, 'Terminee'),
(6, 7, 7, 'Agadir - Zone Portuaire', 'Casablanca - Port', datetime('now', '-2 months'), 'Export agrumes', 8200.00, 'Terminee'),
(8, 10, 8, 'Tanger - Port', 'Algésiras, Espagne', datetime('now', '-2 months'), 'Fret international', 12250.00, 'Terminee'),
(1, 1, 1, 'Casablanca - Port', 'Rabat - Zone Industrielle', datetime('now', '-3 months'), 'Marchandise générale', 7050.00, 'Terminee'),
(2, 2, 3, 'Rabat - Entrepôt AgroFrais', 'Fès - Marché central', datetime('now', '-3 months'), 'Produits frais', 5950.00, 'Terminee'),
(3, 1, 2, 'Marrakech - Dépôt BTP', 'Agadir - Chantier Sud', datetime('now', '-3 months'), 'Matériaux de construction', 9800.00, 'Terminee'),
(1, 4, 1, 'Casablanca - Aïn Sebaâ', 'Tanger - Port', datetime('now', '-3 months'), 'Produits surgelés', 6500.00, 'Terminee'),
(2, 5, 3, 'Rabat - Zone Industrielle', 'Oujda - Entrepôt Est', datetime('now', '-3 months'), 'Marchandise générale', 7000.00, 'Terminee'),
(3, 2, 2, 'Marrakech - Dépôt BTP', 'Safi - Chantier Port', datetime('now', '-3 months'), 'Matériaux de construction', 8650.00, 'Terminee'),
(6, 7, 7, 'Agadir - Zone Portuaire', 'Casablanca - Port', datetime('now', '-3 months'), 'Export agrumes', 8900.00, 'Terminee'),
(8, 10, 8, 'Tanger - Port', 'Algésiras, Espagne', datetime('now', '-3 months'), 'Fret international', 14800.00, 'Terminee'),
(1, 1, 1, 'Casablanca - Port', 'Rabat - Zone Industrielle', datetime('now', '-4 months'), 'Marchandise générale', 7950.00, 'Terminee'),
(2, 2, 3, 'Rabat - Entrepôt AgroFrais', 'Fès - Marché central', datetime('now', '-4 months'), 'Produits frais', 6900.00, 'Terminee'),
(3, 1, 2, 'Marrakech - Dépôt BTP', 'Agadir - Chantier Sud', datetime('now', '-4 months'), 'Matériaux de construction', 9450.00, 'Terminee'),
(1, 4, 1, 'Casablanca - Aïn Sebaâ', 'Tanger - Port', datetime('now', '-4 months'), 'Produits surgelés', 5750.00, 'Terminee'),
(2, 5, 3, 'Rabat - Zone Industrielle', 'Oujda - Entrepôt Est', datetime('now', '-4 months'), 'Marchandise générale', 7850.00, 'Terminee'),
(3, 2, 2, 'Marrakech - Dépôt BTP', 'Safi - Chantier Port', datetime('now', '-4 months'), 'Matériaux de construction', 8700.00, 'Terminee'),
(6, 7, 7, 'Agadir - Zone Portuaire', 'Casablanca - Port', datetime('now', '-4 months'), 'Export agrumes', 9250.00, 'Terminee'),
(8, 10, 8, 'Tanger - Port', 'Algésiras, Espagne', datetime('now', '-4 months'), 'Fret international', 11900.00, 'Terminee'),
(1, 1, 1, 'Casablanca - Port', 'Rabat - Zone Industrielle', datetime('now', '-5 months'), 'Marchandise générale', 8150.00, 'Terminee'),
(2, 2, 3, 'Rabat - Entrepôt AgroFrais', 'Fès - Marché central', datetime('now', '-5 months'), 'Produits frais', 5800.00, 'Terminee'),
(3, 1, 2, 'Marrakech - Dépôt BTP', 'Agadir - Chantier Sud', datetime('now', '-5 months'), 'Matériaux de construction', 9500.00, 'Terminee'),
(1, 4, 1, 'Casablanca - Aïn Sebaâ', 'Tanger - Port', datetime('now', '-5 months'), 'Produits surgelés', 6000.00, 'Terminee'),
(2, 5, 3, 'Rabat - Zone Industrielle', 'Oujda - Entrepôt Est', datetime('now', '-5 months'), 'Marchandise générale', 7500.00, 'Terminee'),
(3, 2, 2, 'Marrakech - Dépôt BTP', 'Safi - Chantier Port', datetime('now', '-5 months'), 'Matériaux de construction', 7800.00, 'Terminee'),
(6, 7, 7, 'Agadir - Zone Portuaire', 'Casablanca - Port', datetime('now', '-5 months'), 'Export agrumes', 9000.00, 'Terminee'),
(8, 10, 8, 'Tanger - Port', 'Algésiras, Espagne', datetime('now', '-5 months'), 'Fret international', 15000.00, 'Terminee');

-- Charges fixes mensuelles des 6 derniers mois
INSERT INTO Charge (Periode, TypeCharge, Montant) VALUES
(date('now', '-0 months', 'start of month'), 'Salaire', 24000.00),
(date('now', '-0 months', 'start of month'), 'Frais', 1900.00),
(date('now', '-0 months', 'start of month'), 'Loyer', 4550.00),
(date('now', '-0 months', 'start of month'), 'Facture', 1200.00),
(date('now', '-0 months', 'start of month'), 'Essence', 5500.00),
(date('now', '-1 months', 'start of month'), 'Salaire', 24100.00),
(date('now', '-1 months', 'start of month'), 'Frais', 1940.00),
(date('now', '-1 months', 'start of month'), 'Loyer', 4600.00),
(date('now', '-1 months', 'start of month'), 'Facture', 1230.00),
(date('now', '-1 months', 'start of month'), 'Essence', 5580.00),
(date('now', '-2 months', 'start of month'), 'Salaire', 24200.00),
(date('now', '-2 months', 'start of month'), 'Frais', 1980.00),
(date('now', '-2 months', 'start of month'), 'Loyer', 4650.00),
(date('now', '-2 months', 'start of month'), 'Facture', 1260.00),
(date('now', '-2 months', 'start of month'), 'Essence', 5660.00),
(date('now', '-3 months', 'start of month'), 'Salaire', 24300.00),
(date('now', '-3 months', 'start of month'), 'Frais', 2020.00),
(date('now', '-3 months', 'start of month'), 'Loyer', 4700.00),
(date('now', '-3 months', 'start of month'), 'Facture', 1290.00),
(date('now', '-3 months', 'start of month'), 'Essence', 5740.00),
(date('now', '-4 months', 'start of month'), 'Salaire', 24400.00),
(date('now', '-4 months', 'start of month'), 'Frais', 2060.00),
(date('now', '-4 months', 'start of month'), 'Loyer', 4750.00),
(date('now', '-4 months', 'start of month'), 'Facture', 1320.00),
(date('now', '-4 months', 'start of month'), 'Essence', 5820.00),
(date('now', '-5 months', 'start of month'), 'Salaire', 24500.00),
(date('now', '-5 months', 'start of month'), 'Frais', 2100.00),
(date('now', '-5 months', 'start of month'), 'Loyer', 4800.00),
(date('now', '-5 months', 'start of month'), 'Facture', 1350.00),
(date('now', '-5 months', 'start of month'), 'Essence', 5900.00);
